### ISSUE TITLE
Missing data in elastic search

### ISSUE THREAD

**Issue by bryantcj52** [logstash-plugins/logstash-input-jmx#15]
I just started using the JMX plugin and I'm missing some metrics in elastic search (Memory.HeapMemoryUsage.\* and Runtime.StartTime).

When I use the stdout debug in logstash, I'm seeing the data but they are missing when going to elastic search. 

Example data received by elastic search:
![image](https://cloud.githubusercontent.com/assets/4873826/12022006/5c1e4d98-ad51-11e5-8a2b-3654efdee650.png)

My JMX config:
<code>{
  "host": "127.0.0.1",
  "port": 1335,
  "alias": "host.name__",
  "queries": [{
    "object_name": "java.lang:type=Memory",
    "object_alias": "Memory"
  }, {
    "object_name" : "java.lang:type=Threading",
    "attributes": ["ThreadCount"],
    "object_alias": "Threading"
  }, {
    "object_name": "java.lang:type=Runtime",
    "attributes": ["Uptime", "StartTime"],
    "object_alias": "Runtime"
  }, {
    "object_name": "java.lang:type=GarbageCollector,name=_",
    "attributes": ["CollectionCount", "CollectionTime"],
    "object_alias": "${type}.${name}"
  }, {
    "object_name": "java.nio:type=BufferPool,name=_",
    "object_alias": "${type}.${name}"
  }]
}</code>

I tried limiting the memory object to only heap memory but that didn't help. Any ideas would be helpful.

Thanks,
Cory

**Comment by jordansissel** [comment]
I'm not sure I understand what problem you are reporting. You said that Elasticsearch is missing data, but your screenshot shows that it has data. I may be misunderstanding, can you clarify?

**Comment by bryantcj52** [comment]
Only specific metrics: (Memory.HeapMemoryUsage.\* and Runtime.StartTime). I have five hosts reporting JMX and those metrics are missing for all five.

**Comment by bryantcj52** [comment]
Turns out the values were too large for the int type in my index. I switched to long and it's working now.

Sorry about that.
