### ISSUE TITLE
Doesn't support the new logstash architecture without contrib files

### ISSUE THREAD

**Issue by evgygor** [logstash-plugins/logstash-input-jmx#2]
This input requires jmx4r gem that not provided "from the box" by logstash-1.5.0.beta1.
My workaround is install jmx4r gem to the jruby directory in logstash:

/opt/logstash/vendor/jruby/bin/jruby -S gem  install --install-dir /opt/logstash/vendor/bundle/jruby/1.9 jmx4r

**Comment by electrical** [comment]
That would be weird since the dependency is specified in the gemspec file.
How did you install the plugin?

**Comment by evgygor** [comment]
My bad, I installed the plugin manually.
Now, I installed via plugin manager by # ./plugin install logstash-input-jmx and jmx4r installed automatically too.

But new issue appeared in logstash log file:

{:timestamp=>"2015-02-03T16:40:13.356000+0200", :message=>"The error reported is: \n  jmx must set a milestone. For more information about plugin milestones, see http://logstash.net/docs/1.5.0.beta1/plugin-milestones "}

Seems that jmx.rb missed line with milestone number.
I added (without quotes) "milestone  1" to the jmx.rb and issues solved.

Thanks

**Comment by electrical** [comment]
Ah sorry about that. the milestone has been removed indeed but is only available in the git clone version as its not released yet. seems we were a bit to fast in releasing the plugins with the change.

**Comment by evgygor** [comment]
Thanks for clarification,
Btw, where can I ask questions about this plugin and others plugins too?

**Comment by electrical** [comment]
if you have questions about a specific plugin it would be best to do that in the specific plugin repo.
if you have something about a non-existing plugin yet or a general plugin question please ask in the logstash repo.
